### ISSUE TITLE
ZIP-321 Payment URIs and deeplinking

### ISSUE THREAD

**Issue by geffenz** [Electric-Coin-Company/zashi-android#146] opened 2021-12-15 21:40 UTC
This Research Spike is about finding how well deep links / universal links work with Zcash Payment URIs defined in https://zips.z.cash/zip-0321

This is a duplicate of the iOS ticket for Android.

**Comment by ccjernigan** [comment] 2022-05-18 13:26
Closing this as a duplicate of #202.

**Closed** 2024-10-29 21:22 UTC
